### PR TITLE
Implementing zone mesh awareness and improving navigation

### LINKED ISSUE #318: Navigation Meshes and Path finding
This issue will be used to track the progress of implementing a new navigation system.

Implement Recast/Detour wrapper and path-finding algorithm based on Dark Star project.
DSP has nav meshes available already.

- [x] Implement Recast/Detour Wrapper
- [x] Create Navigation Mesh Handler
- [x] Implement Path-Finding Algorithms
- [x] Re-work Navigation system to use Nav Mesh path finding.

### PR DESCRIPTION
**Pull request by jondwillis**
This work in progress gives the bot awareness of the zone navigation mesh, and allows it to move freely with way fewer waypoints, while avoiding getting stuck when approaching mobs and returning to waypoints as it often does in its current form.

The navmeshes can be found at 
https://github.com/DarkstarProject/xiNavmeshes
and should be placed in a navmeshes directory aside EasyFarm.exe

### CODE REVIEW

**Comment by raboley** [comment]
I feel like a fool, I spent the last 2 months getting this X,Y coordinate system setting up in my fork for somewhat smart pathfinding. This blows my change out of the water. I will have to look into this more and potentially pull this into my fork. Holy cow will this be better.

**Comment by jondwillis** [comment]
@raboley :) be warned though, the pathfinding is only as accurate as your navmeshes. The ones floating around that were used by darkstar and topaz and other private servers are not very suitable for client side pathfinding, and have tons of bad polygons.

**Comment by raboley** [comment]
> @raboley :) be warned though, the pathfinding is only as accurate as your navmeshes. The ones floating around that were used by darkstar and topaz and other private servers are not very suitable for client side pathfinding, and have tons of bad polygons. (think how many bugs and robot-looking navigation you've seen mobs do over the years)

That is really good info :) I will stick to my blind man coordinate engine then, it is slow until I get more things mapped out, but I know how to make those better, where I would have no idea how to improve the meshes if they aren't perfect.

**Comment by jondwillis** [comment]
https://github.com/xenonsmurf/FFXI-NavMesh-builder

**Comment by raboley** [comment]
Xen0nsmurf has been helping me to get the nav mesh editing skills needed to try and get this going, so I am gunna take a look at this again and hopefully implement it instead of my x,y coord system that falls apart as soon as two points can have the same x,z but different y... which is very common in zones that have multiple floors.

**Comment by Milklessnonipple** [comment]
Can you please explain how to implement this to my current EasyFarm?  I placed the files in the same directory as EasyFarm.exe but the pathing still seems broken. Is there anything else I need to do?

**Comment by joshuateveryday** [comment]
@jondwillis Going to review if you're still around.  I was working on a navmesh pathfinding implementation a million years ago, but seems like you might have it solved here from a cursor glance.

**Comment by joshuateveryday** [comment]
@jondwillis Seems to have problems on live. Pulled, built, added navmeshes for DS.

Few things I see:
1. When recording a route (straight or circular), it records very slowly. 
2. When attempting to Start pathfinding, the route is not reachable.

Haven't dove super deep into the code to see what's causing this, but this isn't ready for PR.

**Comment by SchroedingerHepcat** [comment]
> @jondwillis Seems to have problems on live. Pulled, built, added navmeshes for DS.
> 
> Few things I see:
> 
> 1. When recording a route (straight or circular), it records very slowly.
> 2. When attempting to Start pathfinding, the route is not reachable.
> 
> Haven't dove super deep into the code to see what's causing this, but this isn't ready for PR yet. I'll look into the code a bit to see what's going on in the pathfinding state.
> 
> EDIT:
> 
> I see, it's looking for zone id named mesh files. That fixes the unreachable issue, however, the pathfinding still doesn't really "work". Going to work on a utility to record meshes in-game and see if that makes things work a little better.

@joshuateveryday I pulled this down about a month ago and started playing with it.  I found the "slowly recording" was because it no longer needed dense paths with the new pathing.  It did seem to work once I got zone meshes in, but it wasn't very good about picking paths when things went around sharp corners and obstacles (and the non-dense path recording makes it hard not to need good pathing around corners.

I'm interested in collaborating on this if you'd like.  I've been exploring the various branches from EasyFarm and trying to figure out what all is out there.  It looks like there are a lot of varying improvements to pull in.

**Comment by joshuateveryday** [comment]
> It did seem to work once I got zone meshes in, but it wasn't very good about picking paths when things went around sharp corners and obstacles (and the non-dense path recording makes it hard not to need good pathing around corners.

Probably on account of the poor quality of nav meshes used by DSP.  They were probably auto-generated from the level geometry and never edited.

> I'm interested in collaborating on this if you'd like. I've been exploring the various branches from EasyFarm and trying to figure out what all is out there. It looks like there are a lot of varying improvements to pull in.

Going to be looking into using code from https://github.com/recastnavigation/recastnavigation/tree/master/RecastDemo/Source
to load level geometry, generate, then clean up for first steps so we can actually test the contents of this PR.  Right now we don't know if the pathfinding algorithm is bad or the navmeshes are bad.

Ultimately, going the way of like MMOminion and building out a toolset to build nav meshes in-game might be the solution.

**Comment by rubymatrix** [comment]
@SchroedingerHepcat Want to continue this discussion in Discord?

**Pull request merged**
